header_pages:
  - index.md
  - support.md
  - about.md
  
footer: 'Knock me on Discord : Eniamza#5876>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
google_analytics: UA-167512615-1
