baseURL: "https://enilog-fgwso.ondigitalocean.app/"
title: Enilog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Enilog | Eni' Blog
  description: "Trips, Tricks, Workarounds, Analysis, Philosophies... Aye!"
  keywords: [Blog, Hacks, Tips, Eniamza]
  author: Eni
  # author: ["Me", "You"] # multiple authors
  images: ["https://raw.githubusercontent.com/Eniamza/enilog-source/master/static/opengraph.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "https://github.com/Eniamza/enilog-source/raw/master/static/Eniamza-500x500.png"
    favicon16x16: "https://github.com/Eniamza/enilog-source/raw/master/static/Eniamza-16x16.png"
    favicon32x32: "https://github.com/Eniamza/enilog-source/raw/master/static/Eniamza-32x32.png"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Enilog"
    icon: "https://github.com/Eniamza/enilog-source/raw/master/static/Eniamza-500x500.png"
    iconHeight: 30

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there 🐱 ~ It's Eniamza"
    Content: "Have you been thinking about how to use your toaster and turn it into a spaceship?\n\n\nWell probably not that, but my blog is dedicated to fullfill all your curiosities and beyond!"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/eniamza"
    - name: github
      url: "https://github.com/Eniamza"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/Eniamza/enilog-source/tree/master/content/posts"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
#    - identifier: Enilog
#      name: Enilog
#      url: https://eniamza.github.io
#      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai